{{- if .Values.useAwsCertificate }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-ingress-controller
  annotations:
    kubernetes.io/ingress.class: "alb"
    # Tells the AWS Load Balancer Controller which certificate to use
    # Replace the ARN with your ACM certificate ARN:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.awsCertificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":4000}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - host: mp.maoto.world
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apiinterfaces
                port:
                  number: 4000
  tls:
    - hosts:
        - mp.maoto.world
      secretName: dummy-tls-secret

{{- end }}