{{- if .Values.postgresql.activate }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.host }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.postgresql.host }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.host }}
    spec:
      containers:
        - name: {{ .Values.postgresql.host }}
          image: {{ .Values.global.dockerRegistry }}{{ .Values.postgresql.host }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgresql.port }}
          envFrom:
            - configMapRef:
                name: my-env-config
            - secretRef:
                name: my-env-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}

{{- end }}