apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apiinterfaces
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apiinterfaces
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  {{- range .Values.metrics }}
    - type: {{ .type }}
      resource:
        name: {{ .resource.name }}
        target:
          type: Utilization
          averageUtilization: {{ .resource.targetAverageUtilization }}
  {{- end }}
