{{- if .Values.redis.activate }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: databaseredis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: databaseredis
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60  # Reduce wait time for scaling down to 60s
      policies:
        - type: Percent
          value: 50  # Reduce by 50% at a time (e.g., from 2 → 1 replica)
          periodSeconds: 30  # Check every 30 seconds

{{- end }}