apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiinterfaces.host }}
spec:
  type: {{ if .Values.ingress.enabled }}ClusterIP{{ else }}LoadBalancer{{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.apiinterfaces.host }}
