{{- if .Values.redis.activate }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.host }}
spec:
  type: {{ if .Values.redis.loadbalancer }}LoadBalancer{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.redis.externalPort }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
  selector:
    app: {{ .Values.redis.host }}

{{- end }}