{{- if .Values.apiinterfaces.activate }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiinterfaces.host }}
spec:
  type: {{ if .Values.apiinterfaces.loadbalancer }}LoadBalancer{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.apiinterfaces.externalPort }}
      targetPort: {{ .Values.apiinterfaces.port }}
      protocol: TCP
  selector:
    app: {{ .Values.apiinterfaces.host }}

{{- end }}