apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.host }}
spec:
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    app: {{ .Values.postgresql.host }}
