global:
  dockerRegistry: ""
  registrySecret: registry-secret
  revisionHistoryLimit: 3

image:
  tag: "latest"

apiinterfaces:
  activate: false
  host: apiinterfaces
  port: 8080
  loadbalancer: false
  externalPort: 80

postgresql:
  activate: false
  host: databasepostgre
  port: 5432
  loadbalancer: false
  externalPort: 5432

redis:
  activate: false
  host: databaseredis
  port: 6379
  loadbalancer: false
  externalPort: 6379

pullPolicy: IfNotPresent

useAwsCertificate: false
awsCertificateArn: ""
awsHost: ""