name: Register Webhook

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]
  workflow_dispatch:

jobs:
  set-maoto-webhook:
    # Only run this job if the Deploy workflow completed successfully.
    if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Update Maoto Webhook
        env:
          ENV_SERVER_CONTENT: ${{ vars.ENV_SERVER_CONTENT }}
          SECRETS_SERVER_CONTENT: ${{ secrets.SECRETS_SERVER_CONTENT }}
        run: |
          eval "$(echo "$ENV_SERVER_CONTENT" | tr -d '\r')"
          eval "$(echo "$SECRETS_SERVER_CONTENT" | tr -d '\r')"

          curl -s -X POST "https://mp.maoto.world/set_webhook/${MAOTO_API_KEY}" \
            -d "url=$MAOTO_AGENT_URL"

